server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ed-license?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
      
      
      